# Generated by Django 3.1.4 on 2021-01-05 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_stuff', '0002_auto_20210102_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_post_images/post_picture'),
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='user_post_images/profile_picture')),
                ('bio', models.CharField(blank=True, max_length=101)),
                ('gender', models.CharField(blank=True, max_length=6)),
                ('religion', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(blank=True)),
                ('about_me', models.TextField(blank=True)),
                ('favorite_quotes', models.TextField(blank=True)),
                ('hometown', models.CharField(blank=True, max_length=20)),
                ('current_city', models.CharField(blank=True, max_length=20)),
                ('education', models.TextField(blank=True)),
                ('relationship', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('number_of_friends', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
