# Generated by Django 3.1.4 on 2021-01-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stuff', '0003_auto_20210105_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='religion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
