# Generated by Django 3.1.4 on 2021-01-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stuff', '0007_remove_love_reaction_number_of_loves'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_loved_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
