# Generated by Django 3.1.4 on 2021-01-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stuff', '0008_post_is_loved_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_loved_by_user',
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_love',
            field=models.IntegerField(default=0),
        ),
    ]
