# Generated by Django 3.1.4 on 2021-01-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stuff', '0010_post_is_loved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_loved',
            field=models.BooleanField(default=False),
        ),
    ]
