# Generated by Django 3.1.4 on 2021-01-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stuff', '0013_auto_20210109_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
