# Generated by Django 3.1.4 on 2021-01-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stuff', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_comment',
            field=models.IntegerField(default=0),
        ),
    ]
