# Generated by Django 3.1.4 on 2021-01-11 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_stuff', '0021_auto_20210110_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='love_reaction',
            old_name='user',
            new_name='love_user',
        ),
        migrations.RenameField(
            model_name='love_reaction_on_comment',
            old_name='user',
            new_name='love_user',
        ),
        migrations.AddField(
            model_name='love_reaction',
            name='cool_user',
            field=models.ManyToManyField(related_name='coolingUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='love_reaction_on_comment',
            name='cool_user',
            field=models.ManyToManyField(related_name='coolingUserofcomment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='is_cooled',
            field=models.BooleanField(default=False),
        ),
    ]
