# Generated by Django 3.1.4 on 2021-01-12 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_stuff', '0022_auto_20210111_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='followed_by',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BuddyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_members', models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('i_am_following', models.ManyToManyField(related_name='iamfollowingusers', to=settings.AUTH_USER_MODEL)),
                ('i_send_to', models.ManyToManyField(related_name='isendtoUsers', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pending_users', models.ManyToManyField(related_name='pendingUsers', to=settings.AUTH_USER_MODEL)),
                ('pure_members', models.ManyToManyField(related_name='buddies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
