# Generated by Django 3.1.4 on 2021-01-14 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_stuff', '0023_auto_20210112_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_notification', models.IntegerField(default=0)),
                ('post_id', models.IntegerField(blank=True)),
                ('comment_id', models.IntegerField(blank=True)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_new', models.BooleanField(default=False)),
                ('my_notis', models.ManyToManyField(related_name='noti_obj', to='user_stuff.notification_object')),
                ('owner_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
