# Generated by Django 3.1.4 on 2021-01-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stuff', '0024_notification_object_notificationlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_object',
            name='comment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notification_object',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
